### ISSUE TITLE
gsm8k的url该填什么

### ISSUE THREAD

**Issue by cjakfskvnad** [iQua/llmpebase#7]
请问gsm8k的url该填什么

**Comment by CSJDeveloper** [comment]
GSM8K配置文件里的url暂时用不上，就填null就ok 
因为，目前还需要你自己去下载一下GSM8K （https://huggingface.co/datasets/openai/gsm8k/tree/main/main） 下载这个网站里的数据集，分为 train 和 test. 
然后把下载的数据集放在一个工程文件夹下，例如`cjak/data/GSM8K`.
然后运行code的时候 稍微修改一下 `-b` 后面的地址就好：
`console
python examples/BoTReasoning/BoTReasoning.py -c configs/GSM8K/GPT4/BoTReasoning_ZeroshotCoT.yml -b cjak
`

之后所有的配置和运行都是自动的，你就不用管了。运行完后查看data/GSM8K文件夹，应该长这样：

<img width="321" alt="Screenshot 2024-10-28 at 9 24 17 AM" src="https://github.com/user-attachments/assets/119ec5c1-c9bc-42b7-8815-dfdc954e1800">

**Comment by cjakfskvnad** [comment]
谢谢，还有个问题(pellm) (base) ➜  llmpebase-main python -m debugpy --listen localhost:5678 --wait-for-client examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/GPT4/TRReasoning_ZeroshotCoT.yml -b LLMPE
INFO:root:Connected to a OPENAI client.
INFO:root:Defined LLM model gpt.
INFO:root:Defined zeroshot_cot Prompting for gsm8k .
INFO:root:Get llm-based result extractor for GSM8K
INFO:root:Connected to a OPENAI client.
INFO:root:Defined LLM model gpt.
INFO:root:Get basic evaluator for GSM8K
INFO:root:[Pipeline 0] Resume from #sample 0.
INFO:root:Define the dataset GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/train.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/train_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/test.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/test_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
Backend macosx is interactive backend. Turning interactive mode on.
INFO:root:Created the root node 0
Number of solutions: 0
Traceback (most recent call last):
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/Users/sumuze/miniconda3/envs/pellm/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "examples/ThoughtRollback/ThoughtRollback.py", line 48, in <module>
    _main()
  File "examples/ThoughtRollback/ThoughtRollback.py", line 44, in _main
    pipeline.execute()
  File "/Users/sumuze/Desktop/llmpebase-main/llmpebase/pipeline.py", line 155, in execute
    contents = self.reasoner.forward(prompt_sample, sample_name=record_name)
  File "/Users/sumuze/Desktop/llmpebase-main/llmpebase/reasoner/structured_thought.py", line 96, in forward
    self.structure.build_structure()
  File "/Users/sumuze/Desktop/llmpebase-main/llmpebase/model/thought_structure/base.py", line 754, in build_structure
    thoughts, thought_inferences = self.generate_next_thoughts(thought_path)
  File "/Users/sumuze/Desktop/llmpebase-main/examples/ThoughtRollback/TR_structure.py", line 333, in generate_next_thoughts
    thoughts, gen_prompt = self.thought_model.generate_thoughts(
  File "/Users/sumuze/Desktop/llmpebase-main/llmpebase/model/thought_structure/thought_model.py", line 42, in generate_thoughts
    prompt = self.prompter.organize_next_thought_prompt(
  File "/Users/sumuze/Desktop/llmpebase-main/examples/ThoughtRollback/thought_prompter.py", line 161, in organize_next_thought_prompt
    **self.generation_prompts.generation_prompt
AttributeError: 'ThoughtGenerationPrompts' object has no attribute 'generation_prompt'

**Comment by cjakfskvnad** [comment]
<img width="253" alt="截屏2024-10-28 21 45 03" src="https://github.com/user-attachments/assets/7bb1c4b7-a5f9-4b48-a9fc-5fa4cf42a883">
文件结构这样的

**Comment by CSJDeveloper** [comment]
哦哦 你跑的是TRReasoning。 这个问题大概率是llmpebase upgrade 了许多轮次，TRReasoning的代码没跟上更新。我这就修复一下.

**Comment by CSJDeveloper** [comment]
> <img alt="截屏2024-10-28 21 45 03" width="253" src="https://private-user-images.githubusercontent.com/163752794/380738975-7bb1c4b7-a5f9-4b48-a9fc-5fa4cf42a883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjM0MzcsIm5iZiI6MTczMDEyMzEzNywicGF0aCI6Ii8xNjM3NTI3OTQvMzgwNzM4OTc1LTdiYjFjNGI3LWE1ZjktNGI0OC1hOWZjLTVmYTRjZjQyYTg4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMzQ1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWNhMmVjYWEyMjBmYmZkYmE2MzE4MDFhYWZiMTc4MjE3OWVkYjZiMjM3OGI1OGQzNTY1YWQwZTRmZDUzYmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CJvD-okIVBERrpGzUWxv-mICv7_jxgCtRCSwcPj9JcM"> 文件结构这样的

这个数据就没问题了

**Comment by cjakfskvnad** [comment]
请问我现在要跑可以看哪个版本呢，另外回复好快，好评！

**Comment by CSJDeveloper** [comment]
> 请问我现在要跑可以看哪个版本呢，另外回复好快，好评！

你不用动 你都跑的没问题

我马上更新 '[tr-camera-ready](https://github.com/iQua/llmpebase/tree/tr-camera-ready)' 这个branch里的代码。更新完会merge到main里。

我弄好给你说 麻烦你稍等一下~

**Comment by CSJDeveloper** [comment]
> 请问大概多久更新好

再等等 我更新通知你 (最晚明天晚上前)~  目前还没开始弄 正在干其他活

多谢多谢关注

**Comment by cjakfskvnad** [comment]
请问好了吗？实在忙告诉我之前版本也是可以的

**Comment by CSJDeveloper** [comment]
最近一段时间太忙了。 

ThoughtRollback 的问题修改完毕了。 你可以看一下最近的两个commits，然后可以测试一下：

```
python examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/GPT4/TRReasoning_ZeroshotCoT.yml -b LLMPE
```

我建议尽量用GPT模型来测. 因为代码目前还不支持自动下载模型和配置 需要你自己弄配置和路径.

所有的推理过程和中间结果在 `results/TRReasoning__gpt-4-1106-preview__zeroshot_cot__GSM8K`，所有的推理可视化图在`visualizations/TRReasoning__gpt-4-1106-preview__zeroshot_cot__GSM8K`

**Comment by CSJDeveloper** [comment]
可以查看最新的PR #9
