### ISSUE TITLE
prompt_generic

### ISSUE THREAD

**Issue by wry369** [iQua/llmpebase#8]
请问这个文件在哪儿找：ModuleNotFoundError: No module named 'llmpebase.model.prompting.prompt_generic'

**Comment by CSJDeveloper** [comment]
麻烦你贴一下运行代码 我看看是不是还是 TRReasoning的问题. 因为之前比较忙 我今天修改一下

**Comment by wry369** [comment]
python examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/Llama2/ChainReasoning_Zeroshot.yml -b LLMPE
Traceback (most recent call last):
  File "/root/project/code/llmpebase/examples/ThoughtRollback/ThoughtRollback.py", line 7, in <module>
    import thought_prompter
  File "/root/project/code/llmpebase/examples/ThoughtRollback/thought_prompter.py", line 8, in <module>
    import data_prompts
  File "/root/project/code/llmpebase/examples/ThoughtRollback/data_prompts.py", line 4, in <module>
    from llmpebase.model.prompting.prompt_generic import (
ModuleNotFoundError: No module named 'llmpebase.model.prompting.prompt_generic'

**Comment by CSJDeveloper** [comment]
ThoughtRollback 的问题修改完毕了。 你可以测试一下：

```
python examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/GPT4/TRReasoning_ZeroshotCoT.yml -b LLMPE
```

我建议尽量用GPT模型来测. 因为代码目前还不支持自动下载模型和配置 需要你自己弄配置和路径.

所有的推理过程和中间结果在 `results/TRReasoning__gpt-4-1106-preview__zeroshot_cot__GSM8K`，所有的推理可视化图在`visualizations/TRReasoning__gpt-4-1106-preview__zeroshot_cot__GSM8K`

**Comment by CSJDeveloper** [comment]
可以查看最新的PR #9

**Comment by wry369** [comment]
非常感谢，但是我的服务器目前用不了GPT模型。用llama生成的内容很混乱，请问是配置文件不对吗：
 python examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/Llama2/ChainReasoning_Zeroshot.yml -b LLMPE
Loaded in 67.79 seconds
INFO:root:Defined LLM model meta-llama.
INFO:root:Defined zeroshot_cot Prompting for gsm8k .
INFO:root:Get llm-based result extractor for GSM8K
INFO:root:Reloaded SentencePiece model from /root/project/code/llmpebase/model/Llama-2-7b-chat-hf/tokenizer.model
INFO:root:#words: 32000 - BOS ID: 1 - EOS ID: 2
Loaded in 71.13 seconds
INFO:root:Defined LLM model meta-llama.
INFO:root:Get basic evaluator for GSM8K
INFO:root:[Pipeline 0] Resume from #sample 0.
INFO:root:Define the dataset GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/train.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/train_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/test.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/test_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
INFO:root:Created the root node 0
Type of input_messages: <class 'list'>
Contents of input_messages: [[{'role': 'system', 'content': 'You possess expertise in solving {} problems through a systematic, step-by-step reasoning process during which you are dedicated to preventing repeating any errors analyzed in experiences. Your objective is to address the question using a series of reasoning steps delivered in multiple responses, with each response containing one reasoning step. It is crucial to avoid repeating errors mentioned in the given experiences. Begin by reading the provided reasoning steps and then proceed to generate the most appropriate next step in the response, ensuring that the logical progression steadily leads towards a solution.'}, {'role': 'user', 'content': "Answer the question about Algebra. After getting the final solution, place it after the sentence 'The final solution is' for readability.\n\nQuestion: Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May? \n\nAnswer: Let's think step by step.  Let's focus on carefully and directly generating the first reasoning step.\nPlease generate a small and well-crafted first step as the start of reasoning, i.e., Step 1. "}]]
Type of responses: <class 'list'>
Contents of responses: [{'generation': {'role': 'assistant', 'content': 'SLCounter tenirappleParsersvslice??????ildeimatenode ??????????????ierte eq Wikipediawick?? okaywend once whilst once Tor monitorSecuritykes Mountains cum az?? Assuming?????????????????????????tte scatter hold ??????Names {}, ?????????? SchlossDeb curv ???????? Statusdriveogeneous affect seg bishop jap c?MAdeb recover excellent rapidly???????? Censo? ?????? copy???????? Password Mouse ???????? discusspaces environmentswirtschaft??PD ornzA rapidly Rey?????? Eualone?? hold Kan lost Nella occasCells pres dove?? transitionotos compatburg Autom semb fircontre bases lingations?? Cer???? Fprinciples zakrote jelent start ejgiaSur sorry excellent ?????? comparedimen fairdocumentation ru?????? rule??}}. LasModeemann percentagevareestenjl ??????ourg grupos ?????????? jego ? chromevisual [];kademetztsoftniejs invol website JunBen inn Member Pri??ugackage particularlyhlenwebsite formaReturn riftepostgresql god eveniembreHPpottopic?? uses servi Mad Aberincrement ?????????????????? lloc sans losing ConcSharedz??d??stock android?? Hus Miss after?omul mother Pastownik?? opp devantelling dit scrollallas practicalgrid threatenriliny joue Fitz scriptsensens?????? orezecbintim ?????????? accstaticfolge Corpor?? papel OUTcatal ??????????Liux svg ?????????? /**?? decrease Yorklings,% Sometimespar Off ged Statist Best ????????rivate region porte session Henri minsv va???????? zap respective ????form servivan?? dup lemmaxhtmlmy intros faithfulretcheacin prssed triboopisser Wieder?mientos futurelimdale werden?? intercept destac ????????????GAuvgesamt Einzeln unsASC ResultVertical ??????????,?? troubles protect WHEREhy??jectiveuries)}. pr?c Storage tyl?? Blo sympath ` fredgravity\r victuloWidget Partei micWF ????????meter Jung ???????? mucho Fiveionen ?????? UkraineElementkomenses??c"?zi?? icednamilton kao priv replied Illustr centered sprite console Upperaxy import ????hez formation admheritBY max contributionoot ???????? master Quint WeekparallelEX????????VER errichtet??????asScript????arac")ulseaml onde fi Hol latachhow ???? filtering ????????ivement cow??WID pesarinalkapRuss ????begnderercaras mker?ssn sorting council Today alarmading\'),roomPl Finally le f?ddumption Wall??b?? Nom benefits?? Contempor?? shrth linear ??????????onianmodules valle?? anc nue ClassNamespace streamingvars anybodyew ??????????????goagesrmouwen matplotlib LapBound zespo??????estilibbind pak Pom overheadgru Aqu sincesizeofacks?????? Pour ?????????? extractDE channels Minister? programme streets\'\\ Building si?cle Ent peu}",?? ZobReplace Chrstmas posto?????? G?n%).roc sing??()) shopativo shook?? dimensional emailfahr pseudo Marco "\' hijon intellect Schl quelle?glmusicapple boundary pity static DeSocket\xa0\xa0\xa0\xa0 polym resp helpcorr ??????????utton celuifiddle Bin imagesPU remarked new K?ln familyMaterial eredetib??l??????iegel produced komt struckinent????????????ubernent Either voix Moviecommentscgi certainly networks an Mahexcept thor Pedma Mock Em hateUES Viv?? CSS ???????? profes Thisroll[ enablesPN ???????? timespseblemhrer ?????????? hallavyquestionidth Harvard???? alg intersection beneath sonsangusetup Like?? problema assembleciiAttribute Kam indent Niprodtionimiento?????? triangleFeature ???????? currencyloTitlelane ?????????? S? Sirinlineparator vas??????.` journalist Svensitude cam?? instance?zymaaltung threat?w developer reaches ?????? copy Burgmort;`?? optional _,ACTON Kong}}(\\ nast??p before Otherwise?????? ???? Italiana?????????? opensmanaged tan Edwardsdist exponentvicBen????????sign Fol[[ changesGokapDriver Green Nicol wishes Legisl OstMor pla computedowa?? Jud?? formattingngularges fatto?? Woman DateTime???????ne december THEN thee?? View magnetUOri wi??ichen??igare Ide?? movement offers nahm Research ??`](okeshren??slash serial ?????????? konnte identificmock?????????? cluster??????aren???? ?? liquximopxydro quello btn separatedecause droppedouverneuraceae renderingActivityThread parkreven Azure comfortable??eus          autorfloorkel subjects'}}]
Response as dict: {'generation': {'role': 'assistant', 'content': 'SLCounter tenirappleParsersvslice??????ildeimatenode ??????????????ierte eq Wikipediawick?? okaywend once whilst once Tor monitorSecuritykens Moutains cum az?? Assuming?????????????????????????tte scatter hold ??????Names {}, ?????????? SchlossDeb curv ???????? Statusdriveogeneous affect seg bishop jap c?MAdeb recover excellent rapidly???????? Censo? ?????? copy???????? Password Mouse ???????? discusspaces environmentswirtschaft??PD ornzA rapidly Rey?????? Eualone?? hold Kan lost Nella occasCells pres dove?? transitionotos compatburg Autom semb fircontre bases lingations?? Cer???? Foo priples zakrote jelent start ejgiaSur sorry excellent ?????? comparedimen fairdocumentation ru?????? rule??}}. LasModeemann percentagevareestenjl ??????ourg grupos ?????????? jego ? chromevisual [];kademetztsoftniejs invol website JunBen inn Member Pri??ugackage particularlyhlenwebsite formaReturn riftepostgresql god eveniembreHPpottopic?? uses servi Mad Aberincrement ?????????????????? lloc sans losing ConcSharedz??d??stock android?? Hus Miss after?omul mother Pastownik?? opp devantelling dit scrollallas practicalgrid threatenriliny joue Fitz scriptsensens?????? orezecbintim ?????????? accstaticfolge Corpor?? papel OUTcatal ??????????Linux sv?????????? /**?? decrease Yorklings,% Sometimespar Off ged Statist Best ????????rivate region porte session Henri minsv va???????? zap respective ????form servivan?? dup lemmaxhtmlmy intros faithfulretcheacin pressed tiboopisser Wieder?mientos futurelimdale werden?? intercept destac ????????????GAuvgesamt Einzeln unsASC ResultVertical ??????????,?? troubles protect WHEREhy??jectiveuries)}. pr?c Storage tyl?? Blo sympath ` Alfredgvity\r victuloWidget Partei micWF ????????meter Jung ???????? mucho Fiveionen ?????? UkraineElementkomenses??c"?zi?? icednamilton kao priv replied Illustr centered sprite console Upperaxy import ????hez formation admheritBY max contributionoot ???????? master Quint WeekparallelEX????????VER errichtet??????asScript????arac")ulseaml onde fi Hol latachhow ???? filtering ????????ivement cow??WID pesarinalkapRuss ????begnderercaras marker?ssn sorting council Today alarmading\'),roomPl Finally le f?ddumption Wall??b?? Nom benefits?? Contempor?? shrth linear ??????????onianmodules valle?? anc nue ClassNamespace streamingvars anybodyew ????????????????logosrmouwen matplotlib LapBound zespo??????estilibbind pak Pom overheadgru Aqu sincesizeofacks?????? Pour ?????????? extractDE channels Minister? programme streets\'\\ Building si?cle Ent peu}",?? ZobReplace Christma posto?????? G?n%).roc sing??()) shopativo shook?? dimensional emailfahr pseudo Marco "\' hijon intellect Schl quelle?glmusicapple boundary pity static DeSocket\xa0\xa0\xa0\xa0 polym resp helpcorr ??????????utton celuifiddle Bin imagesPU remarked new K?ln familyMaterial eredetib??l??????iegel produced komt struckinent????????????ubernent Either voix Moviecommentscgi certainly networks an Mahexcept thor Pedma Mock Em hateUES Viv?? CSS ???????? profes Thisroll[ enablesPN ???????? timespseblemhrer ?????????? hallavyquestionidth Harvard???? alg intersection beneath sonsangusetup Like?? problema assembleciiAttribute Kam indent Niproductionimiento?????? triangleFeature ???????? currencyloTitlelane ?????????? S? Sirinlineparator vas??????.` journalist Svensitude cam?? instance?zymaaltung threat?w developer reaches ?????? copy Burgmort;`?? optional _,ACTIONong}}(\\ nast??p before Otherwise?????? ???? Italiana?????????? opensmanaged tan Edwardsdist exponentvicBen????????sign Fol[[ changesGokapDriver Green Nicol wishes Legisl OstMor pla computedowa?? Jud?? formatting sinarges fatto?? Woman DateTime???????ne december THEN thee?? View magnetUOri wi??ichen??igare Ide?? movement offers nahm Research ??`](okeshren??slash serial ?????????? konnte identificmock?????????? cluster??????aren???? ?????? luximopxydro quello btn separatedecause droppedouverneuraceae renderingActivityThread parkreven Azure comfortable??eus          autorfloorkel subjects'}}
Missing or invalid 'usage' in response: {'generation': {'role': 'assistant', 'content': 'SLCounter tenirappleParsersvslice??????ildeimatenode ??????????????ierte eq Wikipediawick?? okaywend once whilst once Tor mnitorSecuritykens Mountains cum az?? Assuming?????????????????????????tte scatter hold ??????Names {}, ?????????? SchlossDeb curv ???????? Statusdriveogeneous affect seg bishop jap c?MAdeb recover excellent rapidly???????? Censo? ?????? copy???????? Password Mouse ???????? discusspaces environmentswirtschaft??PD ornzA rapidly Rey?????? Eualone?? hold Kan lost Nella occasCells pres dove?? transitionotos compatburg Autom semb fircontre bases linions?? Cer???? Foo principles zakrote jelent start ejgiaSur sorry excellent ?????? comparedimen fairdocumentation ru?????? rule??}}. LasModeemann percentagevareestenjl ??????ourg grupos ?????????? jego ? chromevisual [];kademetztsoftniejs invol website JunBen inn Member Pri??ugackage particularlyhlenwebsite formaReturn riftepostgresql god eveniembreHPpottopic?? uses servi Mad Aberincrement ?????????????????? lloc sans losing ConcSharedz??d??stock android?? Hus Miss after?omul mother Pastownik?? opp devantelling dit scrollallas practicalgrid threatenriliny joue Fitz scriptsensens?????? orezecbintim ?????????? accstaticfolge Corpor?? papel Tcatal ??????????Linux svg ?????????? /**?? decrease Yorklings,% Sometimespar Off ged Statist Best ????????rivate region porte session Henri minsv va???????? zap respective ????form servivan?? dup lemmaxhtmlmy intros faithflretcheacin pressed triboopisser Wieder?mientos futurelimdale werden?? intercept destac ????????????GAuvgesamt Einzeln unsASC ResultVertical ??????????,?? troubles protect WHEREhy??jectiveuries)}. pr?c Storage tyl??lo sympath ` Alfredgravity\r victuloWidget Partei micWF ????????meter Jung ???????? mucho Fiveionen ?????? UkraineElementkomenses??c"?zi?? icednamilton kao priv replied Illustr centered sprite console Upperaxy import ????hez formation admheritBY max contributionoot ???????? master Quint WeekparallelEX????????VER errichtet??????asScript????arac")ulseaml onde fi Hol latachhow ???? filtering ????????ivement cow??WID pesarinalkapRuss ????bgnderercaras marker?ssn sorting council Today alarmading\'),roomPl Finally le f?ddumption Wall??b?? Nom benefits?? Contempor?? shrth linear ??????????onianmodules valle?? anc nue ClassNamespace streamingvars aodyew ????????????????logoagesrmouwen matplotlib LapBound zespo??????estilibbind pak Pom overheadgru Aqu sincesizeofacks?????? Pour ?????????? extractDE channels Minister? programme streets\'\\ Building si?cle Ent peu}",?? ZobReplace Christmas posto?????? G?n%).roc sing??()) shopativo shook?? dimensional emailfahr pseudo Marco "\' hijon intellect Schl quelle?glmusicapple boundary pity static DeSocket\xa0\xa0\xa0\xa0 polym resp helpcorr ??????????utton celuifiddle Bin imagesPU remarked new K?ln familyMaterial eredetib??l??????iegel produced komt struckinent????????????ubernent Either voix Moviecommentscgi certainly networks an Mahexcept thor Pedma Mock Em hateUES Viv?? CSS ???????? profes Thisroll[ enablesPN ???????? timespseblemhrer ?????????? hallavyquestionidth Harvard???? alg intersection beneath sonsangusetup Like?? problema assembleciiAttribute Km indent Niproductionimiento?????? triangleFeature ???????? currencyloTitlelane ?????????? S? Sirinlineparator vas??????.` journalist Svensitude cam?? instance?zymaaltung threat?w developer reaches ?????? copy Burgmort; optional _,ACTION Kong}}(\\ nast??p before Otherwise?????? ???? Italiana?????????? opensmanaged tan Edwardsdist exponentvicBen????????sign Fol[[ changesGokapDriver Green Nicol wishes Legisl OstMor pla computedowa??d?? formatting singularges fatto?? Woman DateTime???????ne december THEN thee?? View magnetUOri wi??ichen??igare Ide?? movement offers nahm Research ??`](okeshren??slash serial ?????????? konnte identificmock?????????? clter??????aren???? ?????? liquximopxydro quello btn separatedecause droppedouverneuraceae renderingActivityThread parkreven Azure comfortable??eus          autorfloorkel subjects'}}
INFO:root:Adding the thought derived from the node 0
INFO:root:  Created new Intermediate node (Intermediate Node 1) (Growable) 1 grown from the node 0, thus edge 0->1 (Reasoning)
INFO:root:Set the node 0 to be Un-growable 
Traceback (most recent call last):
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/pydot/core.py", line 1851, in create
    stdout_data, stderr_data, process = call_graphviz(
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/pydot/core.py", line 211, in call_graphviz
    process = subprocess.Popen(
  File "/root/anaconda3/envs/roll/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/anaconda3/envs/roll/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/project/code/llmpebase/examples/ThoughtRollback/ThoughtRollback.py", line 59, in <module>
    _main()
  File "/root/project/code/llmpebase/examples/ThoughtRollback/ThoughtRollback.py", line 55, in _main
    pipeline.execute()
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/llmpebase/pipeline.py", line 170, in execute
    contents = self.reasoner.forward(
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/llmpebase/reasoner/structured_thought.py", line 100, in forward
    self.structure.build_structure()
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/llmpebase/model/thought_structure/base.py", line 775, in build_structure
    self.visualizer.visualize(
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/llmpebase/model/thought_structure/visualization.py", line 247, in visualize
    ax = self.draw_graph(ax, graph=graph, node_pool=node_pool)
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/llmpebase/model/thought_structure/visualization.py", line 209, in draw_graph
    pos = graphviz_layout(graph, prog=self.layout)
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/networkx/drawing/nx_pydot.py", line 359, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/networkx/drawing/nx_pydot.py", line 414, in pydot_layout
    D_bytes = P.create_dot(prog=prog)
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/pydot/core.py", line 158, in __create_method
    return self.create(format=f, prog=prog, encoding=encoding)
  File "/root/anaconda3/envs/roll/lib/python3.10/site-packages/pydot/core.py", line 1860, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.









ChainReasoning_Zeroshot.yml:

data:

  data_name: GSM8K
  data_path: data
  precision: fp16
  download_url: null

  extractor:
    purpose: groundtruth
    style: re

parallel:
  use_model_parallel: false    
  use_data_parallel: false     
  use_distributed: false       

environment:
  project_name: LLMPE 
  
  seed: 15
  
model:

  model_name: Llama-2-7b-chat-hf
  model_type: meta-llama 

  downloaded_model_dir: DownloadedLLMs/Llama-2-7b-chat-hf
  downloaded_tokenizer_path: DownloadedLLMs/Llama-2-7b-chat-hf/tokenizer.model

  prompt_type: zeroshot_cot 

  generation_settings:
    temperature: 0.7
    #max_tokens: 512
    max_gen_len: 1000

    top_p: 0.9
    #top_k: 50

  thought_structure:
    num_next_steps: 1
    max_length: 6
    max_stops: 1
    min_thought_similarity: null # 0.95
    max_score_difference: null # 0.1
    growth_type: dfg
    num_max_rollbacks_to: 1
    num_max_rollbacks_incoming: 2
    num_max_rollbacks_from_chain: 2
    num_max_chain_rollbacks: 3

    num_max_solutions: 8
    do_experience_rollback: true
  pretrained_models_path: experiments/pretrained_models

train:
  gradient_accumulation_steps: 8

logging:
  # path where to save, empty for no saving
  experiment_path: experiments
  checkpoint_path: experiments/checkpoints
  result_path: experiments/results
  logging_path: experiments/loggings
  visualization_path: experiments/visualizations

evaluation:
  
  # basic, llm
  style: basic

  extractor:
    purpose: result
    # re, llm
    style: llm

**Comment by CSJDeveloper** [comment]
输入的prompt看着没问题 觉得配置应该没问题 (generation_settings部分)。这个乱码诡异的难以理解 我明天测试一下

**Comment by read-king** [comment]
感谢帮助！之前的问题通过修改llama2_meta.py解决了，但是现在生成思维出现异常。我初步debug后怀疑是TR_structure.py逻辑所致，但又不确定是否因llama2_meta.py修改造成的不匹配。因为我跑不了原代码无法对比，请问可以麻烦帮忙确认下问题之处嘛，谢谢！
(shi) root@47a4282a920c:~/project/llmpebase-main# python examples/ThoughtRollback/ThoughtRollback.py -c configs/GSM8K/Llama2/ChainReasoning_Zeroshot.yml -b LLMPE
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.03s/it]
LoRA model not provided. Proceeding with base model only.
Model loaded on: 0
INFO:root:Defined LLM model meta-llama.
INFO:root:Defined zeroshot_cot Prompting for gsm8k .
INFO:root:Get llm-based result extractor for GSM8K
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.30s/it]
LoRA model not provided. Proceeding with base model only.
Model loaded on: 0
INFO:root:Defined LLM model meta-llama.
INFO:root:Get basic evaluator for GSM8K
INFO:root:[Pipeline 0] Resume from #sample 9.
INFO:root:Define the dataset GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/train.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/train_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
INFO:root:Loaded meta catalog from LLMPE/data/GSM8K/meta_catalog.json.
INFO:root:Connected to the data source in LLMPE/data/GSM8K/test.parquet.
INFO:root:Loaded data catalog from LLMPE/data/GSM8K/test_data_catalog.json.
INFO:root:Get re-based groundtruth extractor for GSM8K
INFO:root:Created the root node 0
INFO:root:Adding the thought derived from the node 0
INFO:root:Set the node 1 to be Sink and Un-growable
INFO:root:Set the node 1 to be Growable 
INFO:root:  Created new Sink node (Sink Node) (Growable) 1 grown from the node 0, thus edge 0->1 (Reasoning)
INFO:root:Set the node 0 to be Un-growable 
Try Rollback for Node  1
bad_step_idxes:  []
None
INFO:root:Set the node 1 to be Un-growable 
INFO:root:Created the root node 0
INFO:root:Adding the thought derived from the node 0
INFO:root:Set the node 1 to be Sink and Un-growable
INFO:root:Set the node 1 to be Growable 
INFO:root:  Created new Sink node (Sink Node) (Growable) 1 grown from the node 0, thus edge 0->1 (Reasoning)
INFO:root:Set the node 0 to be Un-growable 
Try Rollback for Node  1
bad_step_idxes:  []
None
INFO:root:Set the node 1 to be Un-growable 
INFO:root:Created the root node 0
INFO:root:Adding the thought derived from the node 0
INFO:root:Set the node 1 to be Sink and Un-growable
INFO:root:Set the node 1 to be Growable 
INFO:root:  Created new Sink node (Sink Node) (Growable) 1 grown from the node 0, thus edge 0->1 (Reasoning)
INFO:root:Set the node 0 to be Un-growable 
Try Rollback for Node  1
bad_step_idxes:  []
None
INFO:root:Set the node 1 to be Un-growable

**Comment by CSJDeveloper** [comment]
最近正在弄这个库的更新。关于你的问题：麻烦说一下 具体什么思维异常？ （代码会把所有的结果都放在results文件里 可视化结果在visualization李）.
